package networkmanager

const (
	NM_DEVICE_TYPE_UNKNOWN    = 0
	NM_DEVICE_TYPE_ETHERNET   = 1
	NM_DEVICE_TYPE_WIFI       = 2
	NM_DEVICE_TYPE_MODEM      = 3
	NM_DEVICE_TYPE_BT         = 4
	NM_DEVICE_TYPE_OLT        = 5
	NM_DEVICE_TYPE_WIMAX      = 6
	NM_DEVICE_TYPE_INFINIBAND = 7
	NM_DEVICE_TYPE_BOND       = 8
	NM_DEVICE_TYPE_VLAN       = 9
	NM_DEVICE_TYPE_ADSL       = 10
	NM_DEVICE_TYPE_BRIDGE     = 11
	NM_DEVICE_TYPE_GENERIC    = 12
	NM_DEVICE_TYPE_TEAM       = 13
	NM_DEVICE_TYPE_TUN        = 14
	NM_DEVICE_TYPE_IP_TUNNEL  = 15
	NM_DEVICE_TYPE_MACVLAN    = 16
	NM_DEVICE_TYPE_VXLAN      = 17
	NM_DEVICE_TYPE_VETH       = 18
	NM_DEVICE_TYPE_MACSEC     = 19
	NM_DEVICE_TYPE_DUMMY      = 20
)

// Create a MAP
// {
// 	0: "NM_DEVICE_TYPE_UNKNOWN",
// 	1: "NM_DEVICE_TYPE_ETHERNET",
// 	2: "NM_DEVICE_TYPE_WIFI",
// 	3: "NM_DEVICE_TYPE_UNUSED1",
// 	4: "NM_DEVICE_TYPE_UNUSED2",
// 	5: "NM_DEVICE_TYPE_BT",
// 	6: "NM_DEVICE_TYPE_OLPC_MESH",
// 	7: "NM_DEVICE_TYPE_WIMAX",
// 	8: "NM_DEVICE_TYPE_MODEM",
// 	9: "NM_DEVICE_TYPE_INFINIBAND",
// 	10: "NM_DEVICE_TYPE_BOND",
// 	11: "NM_DEVICE_TYPE_VLAN",
// 	12: "NM_DEVICE_TYPE_ADSL",
// 	13: "NM_DEVICE_TYPE_BRIDGE",
// 	14: "NM_DEVICE_TYPE_GENERIC",
// 	15: "NM_DEVICE_TYPE_TEAM",
// 	16: "NM_DEVICE_TYPE_TUN",
// 	17: "NM_DEVICE_TYPE_IP_TUNNEL",
// 	18: "NM_DEVICE_TYPE_MACVLAN",
// 	19: "NM_DEVICE_TYPE_VXLAN",
// 	20: "NM_DEVICE_TYPE_VETH",
// 	21: "NM_DEVICE_TYPE_MACSEC",
// 	22: "NM_DEVICE_TYPE_DUMMY",
// 	23: "NM_DEVICE_TYPE_PPP",
// 	24: "NM_DEVICE_TYPE_OVS_INTERFACE",
// 	25: "NM_DEVICE_TYPE_OVS_PORT",
// 	26: "NM_DEVICE_TYPE_OVS_BRIDGE",
// 	27: "NM_DEVICE_TYPE_WPAN",
// 	28: "NM_DEVICE_TYPE_6LOWPAN",
// 	29: "NM_DEVICE_TYPE_WIREGUARD",
// 	30: "NM_DEVICE_TYPE_WIFI_P2P",
// 	31: "NM_DEVICE_TYPE_VRF",
// }
